Fix for repeating workouts over the limit - Issue #7
justmedude/pylotoncycle pull request #8
Opened 2021-01-27 20:07 UTC by halfordfan

When retrieving workouts, the page size needs to stay fixed even when pulling a partial page.

2021-01-27 23:50 UTC, justmedude commented
Quick question, what happens if there are no results on the last page (the total number of workouts is exactly divisible by the limit). Does that page return empty, or is there an error?

2021-01-28 14:24 UTC, halfordfan commented
That is a case I have not tested.  This is why I am in management. :-)  I’ll try this today and update as necessary.

2021-01-28 14:57 UTC, halfordfan commented
Ok, I think that's going to do it.  1 will be added to the page count if there is a partial page.

2021-01-28 17:42 UTC, justmedude requested changes
small request
...from one manager to another :)

2021-01-28 17:42 UTC, justmedude commented on pylotoncycle/pylotoncycle.py
> +        pages = ( num_workouts // limit ) + ( num_workouts % limit > 0 )
Small nit, mostly from the standpoint of readability.
How about keeping the original:
```
        pages = num_workouts // limit
        rem = num_workouts % limit
```
and then we can go:
```
if rem > 0:
    # There are still some remaining workouts, so add another page
    # to capture them all
    pages += 1
```

2021-01-28 17:42 UTC, justmedude commented
Btw, really appreciate your contribution!

2021-01-30 22:56 UTC, merged